#ifndef _CERTIFICATES_H_
#define _CERTIFICATES_H_

#ifdef __cplusplus
extern "C"
{
#endif

/* This file is auto-generated by the pycert_bearssl tool.  Do not change it manually.
 * Certificates are BearSSL br_x509_trust_anchor format.  Included certs:
 *
 * Index:    0
 * Label:    SmartCrop
 * Subject:  1.2.840.113549.1.9.1=postmaster@smart-crop.tech,CN=SmartCrop,O=SmartCrop,L=Rawai,ST=Phuket,C=TH
 */

#define TAs_NUM 1

static const unsigned char TA_DN0[] = {
   
};

static const unsigned char TA_RSA_N0[] = {
   
};

static const unsigned char TA_RSA_E0[] = {

};

static const br_x509_trust_anchor TAs[] = {
    {
        { (unsigned char *)TA_DN0, sizeof TA_DN0 },
        BR_X509_TA_CA,
        {
            BR_KEYTYPE_RSA,
            { .rsa = {
                (unsigned char *)TA_RSA_N0, sizeof TA_RSA_N0,
                (unsigned char *)TA_RSA_E0, sizeof TA_RSA_E0,
            } }
        }
    },
};

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ifndef _CERTIFICATES_H_ */
